### ISSUE TITLE
Make term report contents more specific

### ISSUE THREAD

**Issue by imagingbook** [Digital-Media/HgbTermReport#1]
Suggestions by @rru-hgb:
* context of the project (e.g. initial situation, goals/requirements, references (related work)) 
* important project steps (e.g. rationale of architecture or technology stack, design decisions, algorithms used, interesting challenges faced on the way, lessons learned, ...)
* system documentation (architecture, technical design, …) so granular, that someone extern to the project could continue working on it
* summary of the accomplishments
* appendix: user guide, screenshots, installation instructions, …

**Comment by imagingbook** [comment]
Fixed by a8b4a0cd997e1453a88e4f7b8b946e3559b0d644
@rru-hgb Pls. check!

**Comment by rru-hgb** [comment]
Looks good to me!
